---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{.Values.rabbitmq.nameOverride}}-secret
spec:
  data:
    - secretKey: 'rabbitmq-password'
      remoteRef:
        key: {{.Values.rabbitmq.externalSecrets.secretName}}
        property: rabbitmq-password
  refreshInterval: '1h'
  secretStoreRef:
    kind: 'ClusterSecretStore'
    name: 'secretsmanager-secretstore'
  target:
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
    name: {{.Values.rabbitmq.nameOverride}}-secret
